name: Auto Comment on New Issues

on:
  issues:
    types: [opened]

jobs:
  auto-reply:
    runs-on: ubuntu-latest
    # filter on me
    if: github.event.issue.user.login == 'Richard-chanable'

    permissions:
      issues: write

    steps:
      - name: Comment on new issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Test reply'
            })